from __future__ import annotations

from dataclasses import dataclass


@dataclass
class PullRequestDescription:
    """
    Structured pull request content generated by the agent.
    """

    title: str
    body: str


class PRDescriptionBuilder:
    """
    Builds a deterministic pull request description.

    The builder does not call an LLM.

    It converts structured agent information into a
    consistent PR format. An LLM can be introduced later
    as an optional description-generation strategy.
    """

    def build(
        self,
        *,
        title: str,
        summary: str,
        diff_summary: str,
        test_results: str,
    ) -> PullRequestDescription:

        if not title.strip():
            raise ValueError(
                "Pull request title cannot be empty."
            )

        if not summary.strip():
            raise ValueError(
                "Pull request summary cannot be empty."
            )

        if not diff_summary.strip():
            diff_summary = "No diff summary available."

        if not test_results.strip():
            test_results = "No test results available."

        body = (
            "## Summary\n\n"
            f"{summary.strip()}\n\n"
            "## Diff Summary\n\n"
            "```text\n"
            f"{diff_summary.strip()}\n"
            "```\n\n"
            "## Test Results\n\n"
            "```text\n"
            f"{test_results.strip()}\n"
            "```\n\n"
            "## Verification\n\n"
            "- Changes were applied in the isolated workspace.\n"
            "- Tests were executed before creating this pull request.\n"
            "- This pull request was created automatically "
            "by the Autonomous Coding Agent.\n"
        )

        return PullRequestDescription(
            title=title.strip(),
            body=body,
        )